### ISSUE TITLE
buildAccesRequest is not defined

### ISSUE THREAD

**Issue by TheFloydman** [gianluca1606/ups-easy-shipping#1]
Thank you for making this! I'm a newbie, but I've managed to get Square orders and payments working with NodeJS, and I'd like to grab a shipping cost estimate from UPS. I'm following the Rating example, but I am catching a `buildAccesRequest is not defined` error.

**Comment by TheFloydman** [comment]
Opa, figured it out. For whatever reason, it didn't have access to `buildAccesRequest()` in `rating.js`. I'm not sure how this is actually supposed to be taken care of, but I just copied over the method to give it access.

**Comment by TheFloydman** [comment]
Alrighty, learning lots of cool things about this. When I'm done with my specific use case, I'll start submitting some pull requests.

**Comment by gianluca1606** [comment]
> Opa, figured it out. For whatever reason, it didn't have access to `buildAccesRequest()` in `rating.js`. I'm not sure how this is actually supposed to be taken care of, but I just copied over the method to give it access.

You are right I see that i missed to import the function on a few files.
I will fix it later. If you find more bugs feel free to contact me or make a PR like you said.

It is a little bit hard for me to test since I do not have a license key.
